development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sinatra_with_mysql_dev
  pool: 5
  username: root
  password:
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sinatra_template_test
  pool: 5
  username: root
  password:
  
production:
  adapter: mysql2            
  host: 54.208.130.57                         # VM IP
  port: 48668                          # VM Port  
  database: demo_db             # Database Name
  username: a94xepztww52z4gr                # User Name
  password: 'atzzagmjxe428o4h9yartlexylcdh2rs'  
