development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sinatra_with_mysql_dev
  pool: 5
  username: root
  password:
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sinatra_template_test
  pool: 5
  username: root
  password:
  
production:
  adapter: mysql2            
  host: 192.168.3.241                         # VM IP
  port: 11622                          # VM Port 
  database: demo_db             # Database Name
  username: ad3swivaaof11fsw                 # User Name
  password: 'ajsu40byqxqn67801pllyvm8lbt48gsk'                # Password
